#!/usr/bin/env bash

set -e

readonly BASE_URL="https://api.github.com/repos"

show_help() {
    cat <<EOF
    Usage: $(basename "$0") <owner>/<repo_name>

    Fetches the size of a GitHub repo using GitHub API and
    formats it into human readable units

    Arguments:
    <owner>/<repo_name> The target GitHub repository (torvalds/linux)

    Options:
    -h, --help Display this help message and quit
EOF
}

main() {
    local repo_name="$1"

    if [[ -z "$repo_name" ]]; then
        echo "Error: repository name is required" >&2
        echo "Run: '$(basename "$0") -h' for usage information" >&2
        exit 1
    fi

    if [[ "$repo_name" == '-h' || "$repo_name" == '--help' || "$repo_name" == 'help' ]]; then
        show_help
        exit 0
    fi

    local url="$BASE_URL/$repo_name"

    local response
    if ! response=$(curl -sf "$url"); then
        echo "Error: failed to fetch data" >&2
        exit 1
    fi

    local size
    size=$(echo "$response" | jq '.size')

    local formatted_size

    if ((size >= 1024 * 1024)); then # GB
        local gb=$((size / (1024 * 1024)))
        local rem=$(((size % (1024 * 1024)) * 100 / (1024 * 1024)))
        printf -v formatted_size "%d.%02d GB" "$gb" "$rem"
    elif ((size >= 1024)); then # MB
        local mb=$((size / 1024))
        local rem=$(((size % 1024) * 100 / 1024))
        printf -v formatted_size "%d.%02d MB" "$mb" "$rem"
    else
        formatted_size="${size} KB"
    fi

    echo "Size of $repo_name: $formatted_size"
}

main "$@"
